name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      myinput:
        description: "Example input arg"
        required: true
        default: "I am a string"
        type: string
      maxnum:
        description: "Target number to generate Fib. and Primes up to"
        required: true
        default: 1000
        type: number

jobs:
  example-js-action:
    name: "Example-JS-Action Job"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action Dependency"
        # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
        uses: actions/checkout@v4
        with:
          repository: thoughtscript/example-js-action
          token: ${{ secrets.MY_TOKEN }}
          path: ./.github/actions/thoughtscript/example-js-action

      - name: "example-js-action"
        # Execute and run the GitHub JS Action Function - will look for action.yml
        uses: ./.github/actions/thoughtscript/example-js-action/
        with:
          # https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
          myinput: ${{ inputs.myinput }}"
      
      - name: "Checkout GitHub Action Dependency"
        uses: actions/checkout@v4
        with:
          repository: thoughtscript/example-container-action
          token: ${{ secrets.MY_TOKEN }}
          path: ./.github/actions/thoughtscript/example-container-action
  
      - name: "example-container-action"
        uses: ./.github/actions/thoughtscript/example-container-action/
        with:
          maxnum: ${{ inputs.maxnum }}"